### PR TITLE
Add new button labeled 'Save'

### PR DESCRIPTION
**Pull request by kdunn926**
Addresses #11 . An alternative way is to generalize the `PostButton` into a `ConfirmButton` with display text as a parameter? That would collapse `Post`, `Create`, and now `Save` into a single function. I've never done Kotlin development so forgive me is this is sophomoric.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
But is it clear that Save is going to the published in the relay and not locally. That was why I kept Post, to make sure people know this is public.

**Comment by kdunn926** [comment]
I hadn't considered the underlying "persistence" mechanism when opening this PR. I can see your point about using deliberate language to inform the user about both "what and how" rather than simply "what" is being done on that screen.

@bitcoinuser - what do you think?

**Comment by dergigi** [comment]
I assume this is the same as #99?

**Comment by kdunn926** [comment]
It seems like this may not be needed after all. I'm going to close the PR.

**Pull request closed without merging**
