### PR TITLE
Work in progress: Change twitter to x

### PR DESCRIPTION
**Pull request by davotoula**
Some users reported faulty twitter "verification" following change to x.com

Updated UI Twitter references to X and updated code to use x.com URL
Updated twitter drawable to x logo

1. I am not able to invert the colours for x drawable when dark theme is used. @greenart7c3 any help appreciated
2. Should I implement verification of the the pubkey in status message to prevent Twitter impersonations?

### CODE REVIEW

**Comment by greenart7c3** [comment]
I think you need to create a new drawable inside the drawable-night folder for dark theme

**Comment by KotlinGeekDev** [comment]
Please @davotoula anything that made you close this?

**Comment by davotoula** [comment]
I didn't want it hanging until I've made the logo for both light/dark theme. Almost ready!

**Comment by davotoula** [comment]
The branch is there in case you have time to update the logo 😉

**Comment by KotlinGeekDev** [comment]
Oops, sorry, I missed it. Well, it's merged already. :)

> The branch is there in case you have time to update the logo 😉

**Pull request closed without merging**
