### PR TITLE
Crashfix: test for empty string in mentions

### PR DESCRIPTION
**Pull request by davotoula**
Observing a crash when trying to comment on a specific note. Root cause looks a missing hex in the mention tag of the post:

`{
  "id": "2be8bcd50a46628a08523c4b638406e04d1d7ab75c8f9ede5aaaf568e4bde081",
  "pubkey": "20986fb83e775d96d188ca5c9df10ce6d613e0eb7e5768a0f0b12b37cdac21b3",
  "created_at": 1730957039,
  "kind": 1,
  "tags": [
    [
      "p",
      "",
      "",
      "mention"
    ]
  ],`

Event ID: `nevent1qqszh69u659yvc52ppfrcjmrssrwqnga02m4eru7med24atguj77pqgpzamhxue69uhhyetvv9ujumn0wd68ytnzv9hxgtczyqsfsmac8em4m9k33r99e803pnndvylqadl9w69q7zcjkd7d4ssmxqcyqqqqqqgx0u6l0`

The  `isValidHex` function specifically fails empty hexes so I filter out the empty hex mention in the calling `NewPostViewModel` class.

### CODE REVIEW

**Review by KotlinGeekDev — COMMENTED** [review]
Nice, though the root issue I suspect, is the client producing this event. It will probably need to be reported to them.

**Comment by davotoula** [comment]
Yes.. I need to check nostr docs whether empty mentions like that are valid.. Or maybe just not defined.

In any case amethyst should expect malformed messages and not crash. Display a toast to user.. Or just ignore silently?

**Comment by KotlinGeekDev** [comment]
@davotoula you seem not to the only one to have noticed(based on the replies to that note), and from opening it on many clients, most silently ignore it, and render it as is ("@npub1..."). Only Coracle looks for the referenced profile.

**Comment by KotlinGeekDev** [comment]
IMG_20241107_132212
@davotoula seems to work on Amethyst?

**Comment by davotoula** [comment]
That's with the debug build from pull request

**Comment by KotlinGeekDev** [comment]
> That's with the debug build from pull request

This is actually with the latest release build.

**Comment by davotoula** [comment]
@KotlinGeekDev can you please double check? I really don't see how it could work with release build.

Note id: nostr:nevent1qqszh69u659yvc52ppfrcjmrssrwqnga02m4eru7med24atguj77pqgpzamhxue69uhhyetvv9ujumn0wd68ytnzv9hxgtczyqsfsmac8em4m9k33r99e803pnndvylqadl9w69q7zcjkd7d4ssmxqcyqqqqqqgx0u6l0

**Comment by KotlinGeekDev** [comment]
> @KotlinGeekDev can you please double check? I really don't see how it could work with release build.
> 
> Note id: nostr:nevent1qqszh69u659yvc52ppfrcjmrssrwqnga02m4eru7med24atguj77pqgpzamhxue69uhhyetvv9ujumn0wd68ytnzv9hxgtczyqsfsmac8em4m9k33r99e803pnndvylqadl9w69q7zcjkd7d4ssmxqcyqqqqqqgx0u6l0

Got it.

**Comment by davotoula** [comment]
Which reply from above do you think shows it works with latest amethyst release?

**Comment by davotoula** [comment]
By the way, viewing works.

It crashes if you click the create a comment button.

**Comment by KotlinGeekDev** [comment]
> By the way, viewing works.
> 
> It crashes if you click the create a comment button.

Yeah, you're right about that.

**Comment by vitorpamplona** [comment]
It looks good, I just need to get home to do some testing and then merge.

**Pull request merged**
