### PR TITLE
allow relay selection dialog to pick any relays

### PR DESCRIPTION
**Pull request by jeremyd**
Currently, the relay selection dialog only shows "write" relays.  This change allows you to select from any of the relays and override the relay posting engine to allow the messages through.

### CODE REVIEW

**Comment by jeremyd** [comment]
currently still doing some testing, I think this is working, but auth seems broken in main branch?

Also trying to double-check it will not post to nostr.band

**Comment by jeremyd** [comment]
update:  looks like auth works fine, just the relay icons on the note didn't show up (but it did post and another account shows the icon etc).

still need to confirm there is no leakage to nostr.band (tough to tell because of all these relay scrapers these days)..

more soon.

**Comment by jeremyd** [comment]
confirmed, there does not appear to be any leakage.  Just was getting confused from search scrapers like nostr.band grabbing messages via nostr.watch relay lists.

So yeah, this is working!!  Very cool.  Any feedback @vitorpamplona ?

**Comment by vitorpamplona** [comment]
Sorry, I was not able to check this yesterday, but I skimmed over it and it looks great. I will try to merge by Monday.

**Comment by vitorpamplona** [comment]
@jeremyd what's your npub?

**Pull request merged**
