### PR TITLE
843 url previews mishandle html entities

### PR DESCRIPTION
**Pull request by davotoula**
added test to regular expression for html entity numbers
added a few common numerical html entities

#843 
@jiftechnify

### CODE REVIEW

**Comment by vitorpamplona** [comment]
hum... we might need to figure out a way to include all codes in this.. 

&nbsp; can also be written as &#160; (decimal) or &#xa0; (hex)

**Comment by davotoula** [comment]
@vitorpamplona Would you consider using a 3rd party library?

**Comment by davotoula** [comment]
Actually 2 questions..

Thorough and complete html parsing is a project on it's own. Could we leverage an external open source library? 

It seems as if the whole external html document is parsed. We are just showing title and few lines from the document. Maybe it's possible to only parse part of the external html document?

**Comment by vitorpamplona** [comment]
> Could we leverage an external open source library?

Sure, frankly most of these HTML decoders should be inside Java/Kotlin libraries already, I just don't know where to find them or how to use the internal library together with @jiftechnify's fast parser. 

> Maybe it's possible to only parse part of the external html document?

I think these opengraph tags could be anywhere in the head of the document, so we might discard the `body`. But I am frankly not sure about it.

**Comment by jiftechnify** [comment]
I made a misassumption about HTML entity references... I didn't think they are used so wildly in the world. As a consequence, the `MetaTagParser` I introduced in #818 only resolves few basic HTML entity refs:

https://github.com/vitorpamplona/amethyst/blob/main/commons/src/main/java/com/vitorpamplona/amethyst/commons/preview/MetaTagsParser.kt#L133-L166

If there is a library that do the one thing(resolving HTML entity refs), we could leverage it in my parser. I'll look for it.


> It seems as if the whole external html document is parsed. We are just showing title and few lines from the document. Maybe it's possible to only parse part of the external html document?

The `MetaTagsParser` already do this; it only parses `<meta>` tags inside `<head>` tags.

**Comment by davotoula** [comment]
@jiftechnify 
That sounds like the right approach... leveraging an existing library!

Maybe this one would work?

https://github.com/MohamedRejeb/Ksoup

**Comment by vitorpamplona** [comment]
> https://github.com/MohamedRejeb/Ksoup

I am not sure if we should use the entire library, since it might be slower than what @jiftechnify has done. But Ksoup seems to have an entity map: https://github.com/MohamedRejeb/Ksoup/blob/main/ksoup-entities/src/commonMain/kotlin/com/mohamedrejeb/ksoup/entities/EntityMaps.kt

**Comment by davotoula** [comment]
I don't see mapping from hex entities...

**Comment by vitorpamplona** [comment]
> I don't see mapping from hex entities...

Their Numberic Decoder does that before maps are applied: https://github.com/MohamedRejeb/Ksoup/blob/0ac02fe52d500605f9e068da70de582cbe1fa3e5/ksoup-entities/src/commonMain/kotlin/com/mohamedrejeb/ksoup/entities/text/translate/NumericEntityDecoder.kt#L70

**Pull request merged**
