### PR TITLE
feat: enable 100sats as default zap

### PR DESCRIPTION
**Pull request by emidev98**
This pull request enables a default zap of 100 Sats

### CODE REVIEW

**Comment by davotoula** [comment]
What is the reasoning behind this change please?

**Comment by emidev98** [comment]
Hey @davotoula, I just feel like I want to spam people with 100sats and at the moment that option is not available for the app. The first approach I thought about was to code a new screen to allow the user to pick any quantity they want but then I realized that I had not enough time to do that.

**Comment by davotoula** [comment]
If you long hold the zap button you can add or remove zap amounts

**Comment by emidev98** [comment]
LoL! Did not know that! Thanks for that it's being very helpful!

**Pull request closed without merging**
