### PR TITLE
Fix menu drawer in landscape mode issue

### LINKED ISSUE #538: [BUG] Rotating screen to landscape open sidebar menu
**Describe the bug**
When rotating the phone from portrait to landscape, the sidebar menu auto open and hide half the view width.

**To Reproduce**
Open Amethyst app in portrait then rotate it to landscape in the home view

**Expected behavior**
Sidebar navigation should be hidden and only a user action should make it appearing

**Video and Screenshots**
Happy to provide a screenshot if necessary to figure out the bug, let me know :)

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 6A
 - Android Version [e.g. 33]: GrapheneOS
 - App Version [e.g. v0.20.3]: V0.72.0-FDROID

### PR DESCRIPTION
**Pull request by KotlinGeekDev**
This fixes #538 .

### CODE REVIEW

**Comment by KotlinGeekDev** [comment]
cc @vitorpamplona

**Comment by vitorpamplona** [comment]
Nice! thank you @KotlinGeekDev

**Comment by anthony-robin** [comment]
Thank you for fixing the bug @KotlinGeekDev, I tested in the last release and it works like a charm !

**Comment by KotlinGeekDev** [comment]
> Nice! thank you @KotlinGeekDev

:pray:

**Comment by KotlinGeekDev** [comment]
> Thank you for fixing the bug @KotlinGeekDev, I tested in the last release and it works like a charm !

Thanks for the feedback! :pray:

**Pull request merged**
