### PR TITLE
Add media compression level uncompressed

### PR DESCRIPTION
**Pull request by davotoula**
Added Uncompressed media quality level. Skips compression completely and just continues with original media.

[Screen_recording_20240911_173255.webm](https://github.com/user-attachments/assets/2edbeac5-4847-44d4-bc3c-9ce69a9b59a9)

### CODE REVIEW

**Comment by davotoula** [comment]
`Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

Can I fix it or do you have to fix the build workflow @vitorpamplona?

**Comment by vitorpamplona** [comment]
I will fix the `actions/upload-artifact: v2` thing

**Review by KotlinGeekDev — COMMENTED** [review]
Nice! I was actually thinking about this option when you made the previous (introductory) PR, but forgot to ask again about it. :sweat_smile:

**Comment by davotoula** [comment]
Yeah, it's a nice option to have for media creators. Especially with their own media server.

I didn't think about it in the original pull request.

**Comment by KotlinGeekDev** [comment]
> Yeah, it's a nice option to have for media creators. Especially with their own media server.
> 

Exactly.

**Comment by davotoula** [comment]
Loos fixed. thanks @vitorpamplona

**Comment by davotoula** [comment]
This didn't work, no changes were merged 😱.

Maybe it was the last merge from main into the branch that confused the PR merge.

I will create a new PR and redo it.

**Comment by vitorpamplona** [comment]
Are you sure? I can see them on main

**Comment by davotoula** [comment]
I'll triple check

**Comment by davotoula** [comment]
Ah yes, thanks for checking. I didn't update my main 😂😂

**Pull request merged**
