### PR TITLE
auto focus when entering the search screen

### PR DESCRIPTION
**Pull request by VASHvic**
Was searching for easy issues and found this one: https://github.com/vitorpamplona/amethyst/issues/555
I took it as an excuse to keep learning the codebase, feel free to discard if unnecesary!

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Nice! Thank you @VASHvic

**Comment by vitorpamplona** [comment]
What's your npub @VASHvic?

**Comment by VASHvic** [comment]
npub10ug9xs24ay5339agakaqk556t6zvq9qn5vm0vlhc4pu25cx0l32qxhrm9e

**Comment by anthony-robin** [comment]
@vitorpamplona As for the original PR description, what do you think of tagging accessible issues with `Good first issue` label to help newcomers to pick an easy ticket and encourage them more to contribute ? :)

**Pull request merged**
