### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Someone [requested](https://gitlab.com/fdroid/rfp/-/issues/2328) to have your app included with F-Droid, so you will need these metadata (taken from [its listing](https://apt.izzysoft.de/fdroid/index/apk/com.vitorpamplona.amethyst) in my repo). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this (eg adding per-release changelogs, a featureGraphic or additional screenshots).

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Is the directory path a requirement? I'd like to put these inside docs/ if I can

**Comment by IzzySoft** [comment]
It's a requirement, yes. The only alternative for F-Droid would be a shortened variant, but that again had to be in the root (`/metadata/en-US/*`). Doesn't work in subdirectories, sorry.

**Comment by vitorpamplona** [comment]
I just updated the description, logo and new screenshots :) Let's go!

**Comment by IzzySoft** [comment]
Yes sir! Updated the config here and manually initiated an update of the Fastlane structure, so your changes will be reflected with the next sync. Future changes will be pulled whenever a new release was detected. Thanks – and as indicated in #20 be welcome to pick a badge if you want to link there :smiley:

**Pull request merged**
