### PR TITLE
extract strings and add Arabic Language

### PR DESCRIPTION
**Pull request by rashedswen**

### CODE REVIEW

**Comment by rashedswen** [comment]
I don't know how to commit to my existing pull request so I create new one,

**Comment by greenart7c3** [comment]
You just need to commit on your fork and push the commits, then it automatically show in the pull request you made

**Comment by rashedswen** [comment]
ok thanks

**Comment by vitorpamplona** [comment]
Great work, @rashedswen !

**Comment by rashedswen** [comment]
thanks @vitorpamplona

**Pull request merged**
