### PR TITLE
change defaults ConnectivityType to wifi only

### PR DESCRIPTION
**Pull request by greenart7c3**

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Is this a good idea? The default experience without images kind a suck :(

**Comment by greenart7c3** [comment]
Don't know if it's a good idea. I think a lot of people will complain
Maybe we do it after we have a better ui for images and videos

**Comment by KotlinGeekDev** [comment]
Personally, I am not sure it is a good idea. Maybe for this issue, we should run a poll by users?

**Comment by davotoula** [comment]
Personally I love the "media over wifi only" option but I think for new users it would be a poor first user experience.

"wifi only" is for more experienced users.

**Comment by VictorieeMan** [comment]
> Personally I love the "media over wifi only" option but I think for new users it would be a poor first user experience.
> 
> "wifi only" is for more experienced users.

Yeah, unless it looks good for new users it probably isn't a good idea. That's a very good point. The first impression on new users is where they decide to stay or not. That just better look good.

**Comment by greenart7c3** [comment]
I'll close this for now. Maybe when we have a better ui we revisit this.

**Pull request closed without merging**
