### PR TITLE
hide keyboard on resume

### PR DESCRIPTION
**Pull request by davotoula**
workaround for #1166

### CODE REVIEW

**Comment by davotoula** [comment]
This seems to have resolved this issue. 

@vitorpamplona my only guess is that low memory on the device stops and resumes the app occasionally and the `windowSoftInputMode="adjustResize"` pops up the keyboard on each resume.

### Old phones (tried Oreo):
The adjustResize causes the keyboard to always be up when app is resumed. From google docs: _"Android gives focus to the first text field in your layout when the activity starts"._ (https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility)

It looks like the "Status update" field is put in focus and the keyboard is shown.

Exiting a text field does NOT close the keyboard on older phones. 

Using stateHidden will not show keyboard on resume... Even if a text field is in focus (eg. create a not or login screen nsec). One has to click on the text field for keyboard to show up

### Newer phones (tried API 34):
The keyboard is not shown on resume, the "Status update" is not in focus.

If you exit a text field the keyboard is closed automatically.

Only drawback with this change I noticed on newer phones: If you exit app while in a text field and resume the keyboard will not show until you click the text field again.

**Comment by KotlinGeekDev** [comment]
> 
> Only drawback with this change I noticed on newer phones: If you exit app while in a text field and resume the keyboard will not show until you click the text field again.

Interesting. IMHO I don't know if it's much of a drawback though. :thinking:

**Comment by davotoula** [comment]
Just investitigating one more on device workaround before requesting this pull request.

**Comment by KotlinGeekDev** [comment]
> Just investitigating one more on device workaround with the user before requesting this pull request.

Got it.

**Comment by davotoula** [comment]
Marking as ready for merge as the user reported this fix is the only thing that resolves their "popping up-onscreen keyboard" issue on their Samsung A5 Android 8 device.

**Comment by vitorpamplona** [comment]
Hum... isn't this an issue with the status update in the drawer being in focus? That element is not visible so the code for the drawer shouldn't even be running. 

We might need to keep resize there, like on `stateHidden|adjustResize`, but the issue with not showing the keyboard on newer phones if you leave the app on the new post screen is quite annoying.

**Comment by davotoula** [comment]
I agree. There should be a higher percentage of newer phones that benefit from keyboard being closed/open promptly than this fix.

Maybe there is a solution to avoid focus in elements that are not visible. Perhaps using `FocusRequester()` in addition to the `focusManager`.

I'm happy to close this!

**Pull request closed without merging**
