### PR TITLE
Show clickable phone number and nostr:npub reference in markdown notes

### LINKED ISSUE #361: Markdown notes don't render clickable phone numbers and nostr:npub ids
**Describe the bug**
Markdown notes don't render clickable phone numbers and `nostr:npub` ids

**To Reproduce**
Go to this note - nostr://nevent1qqsddksmdd9exsjpz3pmqttr5mjel0mekguvyd6807kqrjzns07pe8q8xr4k5

**Expected behavior**
Clickable phone numbers and nostr:npub like non-markdown notes

**Video and Screenshots**
image

**Device (please complete the following information):**
Android 13

I am working on a PR to fix this.  Will submit in few minutes

### PR DESCRIPTION
**Pull request by vivganes**
fixes #361

Screenshot after fix:

image

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Does clicking on `[@$displayName](nostr://$word)` work? Or do we need a custom URL processor?

**Comment by vitorpamplona** [comment]
Nice! Great work!

**Comment by vitorpamplona** [comment]
What's your pubkey?

**Comment by vivganes** [comment]
> What's your pubkey? 

`npub1ltx67888tz7lqnxlrg06x234vjnq349tcfyp52r0lstclp548mcqnuz40t`

**Comment by vivganes** [comment]
> Nice! Great work! 

Thanks @vitorpamplona 🙏

**Comment by vitorpamplona** [comment]
Btw, if you want to keep going with this, I would love to always use the markdown renderer and delete the other non-markdown implementation. 

We just need feature parity between them.

**Comment by vivganes** [comment]
> Btw, if you want to keep going with this, I would love to always use the markdown renderer and delete the other non-markdown implementation.
> 
> We just need feature parity between them.

One challege is that markdown renderer can be quite restrictive at times.  For example, there is no way to display a button in markdown.  This will make it difficult to show the lightning invoices and all. 

But may be there is a way. Let me do some research and come back.

**Pull request merged**
