### PR TITLE
Fix looong buttons due to localization

### PR DESCRIPTION
**Pull request by Radiokot**
In some languages, words and phrases are longer than in English which leads to UI issues (looong buttons, unwanted word wrap). This pull request:
- Fixes word wrapping in the terms checkbox on the login screen
- Rearranges buttons on the new post screen and adds icons to get more space

 <p float="left">

</p>

<p float="left">

</p>

### CODE REVIEW

**Comment by maxmoney21m** [comment]
The image upload looks nice there, I wonder if text can be removed since the "add media" icon is clear. Maybe the Post button can also come down and be a button at that height. Maybe we could make that a small bottomsheet style card with an elevation, with the two buttons on it and possibility add another button or two later.

**Comment by Radiokot** [comment]
> Maybe the Post button can also come down and be a button at that height. Maybe we could make that a small bottomsheet style card with an elevation, with the two buttons on it and possibility add another button or two later

Would you mind drawing a sketch to illustrate your idea?

**Comment by Chemaclass** [comment]
After merging https://github.com/vitorpamplona/amethyst/pull/220 you will encounter conflicts in this PR. Don't worry. To resolve them simply: 
1) merge `main` into your branch (`fix/looong_buttons`)
2) take all **your** changes (ignoring the others)
3) run `./gradlew ktlintFormat` to make sure you have the code style standard of the project
4) commit and push; you shouldn't have more conflicts of this kind

**Comment by vitorpamplona** [comment]
I wonder how hard this view is to create (only shows after the user has granted permissions)

**Comment by Radiokot** [comment]
Guys, let's merge the fixes (issues with long words and phrases are obvious) and then work on visual improvements, shall we?

**Comment by vitorpamplona** [comment]
Agree, can you resolve those conflicts?

**Comment by Radiokot** [comment]
- Resolved conflicts
- The new code has been formatted by ktLint
- Fixed shrinking of public channel names

<p float=left>


</p>

**Pull request merged**
