### PR TITLE
Added animations

### PR DESCRIPTION
**Pull request by geovnn**
Related to #1126. I added some animations.
&nbsp;

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Very cool! Thank you @geovnn

**Comment by vitorpamplona** [comment]
Actually, what's your npub?

**Comment by geovnn** [comment]
npub1xcl47srtwh4klqd892s6fzwtdfm4y03wzjfl78scmmmxg8wzsf4qftd0en

**Comment by davotoula** [comment]
No lightning address 😱

**Comment by geovnn** [comment]
added :D

**Pull request merged**
