### PR TITLE
Change magnifying glass to globe for global/search tab on AppBottomBar

### PR DESCRIPTION
**Pull request by maxmoney21m**
Created properly sized pngs using svg provided by 3j2009 in #183

Reference screenshot:

image

### CODE REVIEW

**Comment by vitorpamplona** [comment]
This is so much better...

**Comment by 3j2009** [comment]
looks great!

**Comment by braydonf** [comment]
FWIW: For those that turn off all global so as to not be spammed, this tab really only functions to add new public keys.

**Comment by maxmoney21m** [comment]
> FWIW: For those that turn off all global so as to not be spammed, this tab really only functions to add new public keys.

You can add paid relays as read-only for free. Try adding wss://eden.nostr.land and see if your global isn't spam-free.

**Pull request merged**
