### PR TITLE
Update MainActivity.kt

### PR DESCRIPTION
**Pull request by rashedswen**
this line prevent app from crash when change language to Arabic

### CODE REVIEW

**Comment by vitorpamplona** [comment]
I don't get it. Why is this crashing? It forces english, which then disables the translations, no?

**Comment by rashedswen** [comment]
in my case it doesn't force English 

app crashing cause RoboHash return asset string in Arabic ( `sets/set1/red/01Body/red_body-٠٢.png` ) not English ( `sets/set1/red/01Body/red_body-02.png` ) this cause exception file not found.

**Comment by vitorpamplona** [comment]
Well, if we force English then Autotranslations of the post fail... We have to figure out how to fix this robohash issue

**Comment by rashedswen** [comment]
ok we need to focus in this line and functions behave it 

`      defaultAvatar = robots.imageForHandle(robots.calculateHandleFromUUID(UUID.nameUUIDFromBytes("aaaa".toByteArray()))).asImageBitmap()
`

**Comment by vitorpamplona** [comment]
I just sent a quick fix for RoboHash, see if it still crashes

**Comment by rashedswen** [comment]
nice this work well now

**Comment by rashedswen** [comment]
thanks for all your hard work

**Comment by vitorpamplona** [comment]
What's your npub, @rashedswen?

**Comment by rashedswen** [comment]
sorry for late replay 

npub1twcvdqpwkgfvw7dakadzp5ehrde2hzrvgs8nexzpy3de304pfjzs3dy8z2

**Pull request closed without merging**
