### PR TITLE
Oss push notifications(using UnifiedPush)

### PR DESCRIPTION
**Pull request by KotlinGeekDev**
Potentially solves #483 and #494 .

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Hum.. why was the Notification Screen split between flavors?

**Comment by KotlinGeekDev** [comment]
> Hum.. why was the Notification Screen split between flavors? Take a look at the strategy we use for TranslatableRichTextViewer.kt where one is just an empty component from the other.

OK let me take a look.

**Comment by KotlinGeekDev** [comment]
Oh, I see what you mean.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona  done.

**Comment by KotlinGeekDev** [comment]
For this to work, [this PR](https://github.com/vitorpamplona/amethyst-push-notif-server/pull/2) should be merged as well.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona This PR is ready as well. :)

**Comment by vitorpamplona** [comment]
I am confused. What should happen here? 

Screenshot 2023-10-26 at 5 19 44 PM

**Comment by vitorpamplona** [comment]
ohhh I am supposed to install Nfty... I need to adjust this

**Comment by KotlinGeekDev** [comment]
> ohhh I am supposed to install Nfty... I need to adjust this

Yeah, you need Ntfy.

**Comment by KotlinGeekDev** [comment]
> ohhh I am supposed to install Nfty... I need to adjust this

@vitorpamplona that's weird, the dialog should not show when you don't have a distributor.

**Comment by KotlinGeekDev** [comment]
Will make a fix for that now.

**Comment by vitorpamplona** [comment]
No worries, I am modifying a few things as well.

**Comment by KotlinGeekDev** [comment]
> No worries, I am modifying a few things as well.

OK, should I wait for your fixes first?

**Comment by vitorpamplona** [comment]
yes, please.

**Comment by vitorpamplona** [comment]
Just commited, see if it works well for you.

**Comment by KotlinGeekDev** [comment]
> Just commited, see if it works well for you.

Ok.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona That works well for me!

**Pull request merged**
