### PR TITLE
Support for custom media upload servers

### LINKED ISSUE #734: [FEATURE] Ability to customize media upload servers
**Is your feature request related to a problem? Please describe.**
Thanks for the push for NIP-96, highly appreciate it!
I want to self-host nostrcheck or void.cat so I can conveniently upload media files to my own server, not depending on external services. Amethyst is already compatible with these, but does not seem to allow customizing the server URL without recompiling

**Describe the solution you'd like**
Ability to add own media hosting server, maybe by choosing an existing API compatibility.

### PR DESCRIPTION
**Pull request by KotlinGeekDev**
Fixes #734 .

### CODE REVIEW

**Comment by KotlinGeekDev** [comment]
cc @vitorpamplona

**Comment by KotlinGeekDev** [comment]
All conflicts resolved now. Should be OK.

**Comment by vitorpamplona** [comment]
Super nice, Thank you @KotlinGeekDev

**Comment by KotlinGeekDev** [comment]
@vitorpamplona would like to make a follow-up PR on this, to add an "added" status indicator to the hard-coded media servers if they are already present in the user's list.

**Pull request merged**
